# Generated by Django 3.2.8 on 2021-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211016_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Stopped')], default='A', max_length=1),
        ),
    ]
