# Generated by Django 3.2.8 on 2021-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='vk_link',
            field=models.URLField(default='https://vk.com'),
        ),
    ]
