# Generated by Django 3.2.8 on 2021-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211127_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Blocked')], default='A', max_length=1),
        ),
    ]
