# Generated by Django 3.2.8 on 2021-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tguser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_by', to='api.TgUser'),
        ),
    ]
