# Generated by Django 3.2.8 on 2022-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211211_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin')], default='U', max_length=1),
        ),
    ]
